import{db,roomPath,ref,onValue,ensureRoom,normalize,sortSeats,esc}from'./common.js';
const $=id=>document.getElementById(id),sheets=$('placecardSheets');
await ensureRoom();let seats={},side='duplex',filter='confirmed';
onValue(ref(db,roomPath('seats')),s=>{seats=normalize(s.val());render()});
function menuUrl(){return new URL('menu.html',location.href).href.split('?')[0]}
function list(){return Object.values(seats).filter(s=>s.guestName&&(filter==='all'||s.confirmed)).sort(sortSeats)}
function makeFront(chunk){const page=document.createElement('div');page.className='placecard-page placecard-front-page';chunk.forEach(s=>{const card=document.createElement('div');card.className='placecard-row';card.innerHTML=s?`<div class="placecard-panel seat-panel"><span class="placecard-kicker">SEAT</span><strong>${esc(s.id)}</strong></div><div class="placecard-fold-line"></div><div class="placecard-panel name-panel"><span class="placecard-kicker">GUEST</span><div class="placecard-fullname">${esc(s.guestName)}</div></div>`:`<div class="placecard-panel"></div><div class="placecard-fold-line"></div><div class="placecard-panel"></div>`;page.appendChild(card)});return page}
function makeBack(chunk){const page=document.createElement('div');page.className='placecard-page placecard-back-page';chunk.forEach(s=>{const card=document.createElement('div');card.className='placecard-row';card.innerHTML=s?`<div class="placecard-panel menu-label-panel"><img src="assets/color-logo.png" alt="event logo"><strong>DINNER MENU</strong><span>View the full buffet selection</span></div><div class="placecard-fold-line"></div><div class="placecard-panel menu-qr-panel"><div class="menu-placecard-qr"></div><strong>SCAN TO VIEW MENU</strong></div>`:`<div class="placecard-panel"></div><div class="placecard-fold-line"></div><div class="placecard-panel"></div>`;page.appendChild(card);if(s)new QRCode(card.querySelector('.menu-placecard-qr'),{text:menuUrl(),width:118,height:118,correctLevel:QRCode.CorrectLevel.H})});return page}
function fitNames(){document.querySelectorAll('.placecard-fullname').forEach(el=>{let n=23;el.style.fontSize=n+'pt';while(n>12&&(el.scrollWidth>el.clientWidth||el.scrollHeight>el.clientHeight)){n-=.5;el.style.fontSize=n+'pt'}})}
function render(){const a=list();sheets.innerHTML='';const source=a.length?a:[null];for(let i=0;i<source.length;i+=3){const chunk=source.slice(i,i+3);while(chunk.length<3)chunk.push(null);if(side==='duplex'||side==='front')sheets.appendChild(makeFront(chunk));if(side==='duplex'||side==='back')sheets.appendChild(makeBack(chunk))}duplexBtn.classList.toggle('active',side==='duplex');frontBtn.classList.toggle('active',side==='front');backBtn.classList.toggle('active',side==='back');confirmedBtn.classList.toggle('active',filter==='confirmed');allBtn.classList.toggle('active',filter==='all');requestAnimationFrame(fitNames)}
duplexBtn.onclick=()=>{side='duplex';render()};frontBtn.onclick=()=>{side='front';render()};backBtn.onclick=()=>{side='back';render()};confirmedBtn.onclick=()=>{filter='confirmed';render()};allBtn.onclick=()=>{filter='all';render()};printBtn.onclick=()=>window.print();
