import{db,roomPath,roomId,ref,onValue,ensureRoom,normalize,sortSeats,qrPayload,esc,get,set,createCloudBackup,defaultRoom,isGiftEligible}from'./common.js?v=20260921-fixv2';
const $=id=>document.getElementById(id);
const ticketSheets=$('ticketSheets'),printBtn=$('printBtn'),confirmedBtn=$('confirmedBtn'),allBtn=$('allBtn'),standardBtn=$('standardBtn'),giftBtn=$('giftBtn'),ticketDescription=$('ticketDescription'),ticketCounts=$('ticketCounts'),exportBtn=$('exportBtn'),restoreBtn=$('restoreBtn'),importBtn=$('importBtn'),importFile=$('importFile'),resetBtn=$('resetBtn');
await ensureRoom();
let seats={},filter='confirmed',type='standard';
onValue(ref(db,roomPath('seats')),s=>{seats={...defaultRoom().seats,...normalize(s.val())};render();},err=>{console.error(err);seats=defaultRoom().seats;render();});
function baseList(){const all=Object.values(seats).sort(sortSeats);return filter==='confirmed'?all.filter(s=>s.confirmed):all}
function classified(){const a=baseList();return type==='gift'?a.filter(isGiftEligible):a.filter(s=>!isGiftEligible(s))}
function mainMarkup(s){return `<div class="ticket-left"><div class="ticket-logo-box"><img src="assets/color-logo.png" alt="event logo"></div><div><div class="ticket-seat">${esc(s?.id||'')}</div><div class="ticket-guest">${esc(s?.guestName||'')}</div></div></div><div class="ticket-right"><div class="ticket-qr"></div><div class="ticket-info">${s?'QR READY':''}</div></div>`}
function addQr(card,s){if(!s)return;new QRCode(card.querySelector('.ticket-qr'),{text:qrPayload(s),width:118,height:118,correctLevel:QRCode.CorrectLevel.M})}
function renderStandard(list){const source=list.length?list:[null];for(let start=0;start<source.length;start+=10){const chunk=source.slice(start,start+10);while(chunk.length<10)chunk.push(null);const page=document.createElement('div');page.className='ticket-page standard-ticket-page';const grid=document.createElement('div');grid.className='ticket-grid standard-ticket-grid';chunk.forEach(s=>{const card=document.createElement('div');card.className='ticket standard-ticket';card.innerHTML=mainMarkup(s);grid.appendChild(card);addQr(card,s)});page.appendChild(grid);ticketSheets.appendChild(page)}}
function renderGift(list){const source=list.length?list:[null];for(let start=0;start<source.length;start+=8){const chunk=source.slice(start,start+8);while(chunk.length<8)chunk.push(null);const page=document.createElement('div');page.className='ticket-page gift-ticket-page';const grid=document.createElement('div');grid.className='gift-ticket-grid';chunk.forEach(s=>{const card=document.createElement('div');card.className='gift-ticket';const main=document.createElement('div');main.className='ticket gift-ticket-main';main.innerHTML=mainMarkup(s);const stub=document.createElement('div');stub.className='gift-stub';stub.innerHTML=`<div class="tear-guide"><span>✂</span></div><div class="gift-stub-content">${s?`<img src="assets/varx-logo.png" alt="VARX"><div class="gift-wording"><strong>GIFT REDEMPTION</strong><span>${esc(s.id)}</span></div>`:''}</div>`;card.append(main,stub);grid.appendChild(card);addQr(main,s)});page.appendChild(grid);ticketSheets.appendChild(page)}}
function render(){const all=Object.values(seats),confirmed=all.filter(s=>s.confirmed),standardConfirmed=confirmed.filter(s=>!isGiftEligible(s)).length,giftConfirmed=confirmed.filter(isGiftEligible).length;ticketCounts.innerHTML=`<span>Confirmed standard: <b>${standardConfirmed}</b></span><span>Confirmed gift redemption: <b>${giftConfirmed}</b></span>`;const list=classified();ticketSheets.innerHTML='';document.body.classList.toggle('gift-mode',type==='gift');standardBtn.classList.toggle('active',type==='standard');giftBtn.classList.toggle('active',type==='gift');confirmedBtn.classList.toggle('active',filter==='confirmed');allBtn.classList.toggle('active',filter==='all');ticketDescription.textContent=type==='gift'?'Gift redemption ticket · main card remains 85 × 50 mm · 8 per A4':'Standard name-card ticket · 85 × 50 mm · 10 per A4';if(type==='gift')renderGift(list);else renderStandard(list)}
standardBtn.onclick=()=>{type='standard';render()};giftBtn.onclick=()=>{type='gift';render()};confirmedBtn.onclick=()=>{filter='confirmed';render()};allBtn.onclick=()=>{filter='all';render()};printBtn.onclick=()=>window.print();
exportBtn.onclick=async()=>{const s=await get(ref(db,roomPath()));const b=new Blob([JSON.stringify(s.val(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`ballroom-${roomId}-backup.json`;a.click();URL.revokeObjectURL(a.href)};
importBtn.onclick=()=>importFile.click();importFile.onchange=async e=>{await createCloudBackup('before-import');await set(ref(db,roomPath()),JSON.parse(await e.target.files[0].text()))};restoreBtn.onclick=()=>alert('Restore backups from Admin page.');resetBtn.onclick=()=>alert('Reset is available from Admin page.');
